resources:
- repo: self
  clean: true

- job: 'Build test result'

  steps:

  - bash: |
    # Hacking the test system, to remove test using legacy test framework
    rm -rf azure-servicemanagement-legacy azure-servicebus

    source ./testing/bin/activate
    pytest --junitxml=junit.xml

    displayName: Pytest

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '*.xml'



